name: Android Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Lấy mã nguồn
        uses: actions/checkout@v3

      - name: Cài Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cấp quyền chạy gradlew
        run: chmod +x ./gradlew

      - name: Build app
        run: ./gradlew assembleRelease

      - name: Lưu file APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: '**/release/*.apk'
